### ISSUE TITLE
Adaptador de Rede

### ISSUE THREAD

**Issue by ewertont** [Rocketseat/expo-common-issues#1]
Pode acontecer também de ao iniciar o yarn start (expo) o mesmo pegar o endereço de IP de um outro adaptador, exemplo: um adaptador do virtual box fazendo com que seja inciado em uma faixa de IP que não ficará accessível pelo celular físico.

A solução que achei mais fácil foi somente desativar enquanto programava/estudava o adaptador em questão.

**Comment by jcagz96** [comment]
para o problema "Network response timed out" , pode ser tb por terem instalado o wireshark e com ele o Npcap( este interfere com a firewall), o meu conselho é desinstalar o Npcap

**Comment by ruanpablom** [comment]
Mesmo alterando o model com o ip da rede a imagem não aparece nem no dispositivo fisico e nem no android emulado

**Comment by fhugoduarte** [comment]
Obrigado pela contribuição, as informações foram adicionadas ao documento: https://github.com/Rocketseat/expo-common-issues#network-response-timed-out
