### ISSUE TITLE
Não carrega a imagem

### ISSUE THREAD

**Issue by ruanpablom** [Rocketseat/expo-common-issues#2]
Mesmo alterando o model com o ip da rede, não exibe a imagem nem no dispositivo fisico e nem no android emulado, porém quando abro no navegador a imagem aparece

**Comment by Jeffeso-paxao** [comment]
Não ta carregando as imagens dos spots no meu expo pelo meu Celular, e no site estava tudo ok.

**Comment by RonaldoAntonucci** [comment]
Eu tive o mesmo problema.
Vai no seu back-end, na pasta models o arquivo Spot.js, verifica onde vc definiu o seu 'thumbnail_url',
vc provavelmente colocou `http://localhost:3333/files/${this.thumbnail}`.

mude o localhost para o ip que a sua máquina está na rede,
exemplo: `http://192.168.2.33:3333/files/${this.thumbnail}`

**Comment by FelipePLima** [comment]
@RonaldoAntonucci Resolvido! Valeu Amigo!

**Comment by Jeffeso-paxao** [comment]
> Eu tive o mesmo problema.
> Vai no seu back-end, na pasta models o arquivo Spot.js, verifica onde vc definiu o seu 'thumbnail_url',
> vc provavelmente colocou `http://localhost:3333/files/${this.thumbnail}`.
> 
> mude o localhost para o ip que a sua máquina está na rede,
> exemplo: `http://192.168.2.33:3333/files/${this.thumbnail}`

Deu certo vlw!

**Comment by Devjonasbt** [comment]
Mesmo alterando o model com o ip da rede, não exibe a imagem nem no dispositivo fisico e nem no android emulado, porém quando abro no navegador a imagem aparece
