### ISSUE TITLE
Logo ou Texto aparecendo atrás das barra de status no Android

### ISSUE THREAD

**Issue by allyson7** [Rocketseat/expo-common-issues#3]
> Logo ou Texto aparecendo atrás das barra de status no Android
> O Expo muda a cor da barra de status do Android para transparente por padrão, e isso faz com que o comportamento dos elementos funcione igual no iOS, porém a SafeAreaView não funciona no Android. A forma mais rápida de resolver isso é adicionando as seguintes linhas no seu arquivo app.json:
> {
>   "expo": {
>     ...
>     //adicione as linhas abaixo
>     "androidStatusBar": {
>       "barStyle": "dark-content",
>       "backgroundColor": "#ffffff"
>     },
>   }
> }

Mesmo fazendo essas alterações a logo continua atrás do statusbar, não há nenhuma alteração na statusbar, nem da cor do texto,

o que está resolvendo por enquanto é um paddingTop no styles do container pra ser igual à StatusBar.currentHeight, mas sei que pode dar problema em dispositivos diferentes.

**Comment by adrianoapj** [comment]
Sofro do mesmo problema, haha.

**Comment by lukemorales** [comment]
@allyson7 @adrianoapj passou despercebido quando adicionei a informação no documento, mas faltou informar de que após adicionar as linhas no `app.json` você deve parar o Metro Bundler apertando `Ctrl + C` no terminal e iniciar novamente.

O documento já foi alterado com as informações, então vou fechar a issue! Se faltar mais alguma coisa, fiquem a vontade para nos informar ;)

**Comment by adrianoapj** [comment]
Eu fiz isso, e mesmo assim o problema persiste.

**Comment by lukemorales** [comment]
Essa solução deveria ser o suficiente pra resolver o problema... Em último caso, você adicionar um paddingTop com a altura da StatusBar:

```js
import { Platform, StatusBar } from 'react-native';

container: {
	...estilos do vídeo
	paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
}
```

**Comment by adrianoapj** [comment]
Problema resolvido, na realidade tinha sido erro meu, haha. Valeu pela ajuda!

**Comment by allyson7** [comment]
> @allyson7 @adrianoapj passou despercebido quando adicionei a informação no documento, mas faltou informar de que após adicionar as linhas no `app.json` você deve parar o Metro Bundler apertando `Ctrl + C` no terminal e iniciar novamente.
> 
> O documento já foi alterado com as informações, então vou fechar a issue! Se faltar mais alguma coisa, fiquem a vontade para nos informar ;)

Está correto, este procedimento resolveu, muito obrigado

**Comment by euRobertoDias** [comment]
lukemorales,  Essa dica foi muito valiosa cara, vlws!
