### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by FelipePLima** [Rocketseat/expo-common-issues#6]
Estou com um problema, quando faço a requisição pelo mobile, ele aparece só a primeira requisição no appWeb, quando retorno para o APPMob, com o aceito ou rejeitado, se tento criar mais uma reserva, ele não aparece no meu AppWeb e não dá erro em nenhum app, alguém passou por isso?

Valeu

**Comment by jpedroschmitz** [comment]
Fala @FelipePLima, esse repositório foi criado com o objetivo de listar erros mais comuns com o Expo 🎉  Se tiver algum que você acredita que várias pessoas possam ter também, não esquece de abrir um issue para a galera compartilhar soluções 💜 Por tal motivo não vamos poder te ajudar. Se for algo relacionado a Semana OmniStack você pode mandar lá na seção de comentários da página de aulas que alguém vai te dar um ajudar. Abraço 👊
